//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerithium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AerithiumDB1Entities : DbContext
    {
        public AerithiumDB1Entities()
            : base("name=AerithiumDB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<Characters_Specialisations> Characters_Specialisations { get; set; }
        public virtual DbSet<Combat_Roles> Combat_Roles { get; set; }
        public virtual DbSet<Event_Signups> Event_Signups { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<People_Characters> People_Characters { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Signup_Status> Signup_Status { get; set; }
        public virtual DbSet<Specialisations> Specialisations { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Classes_Specialisations> Classes_Specialisations { get; set; }
    }
}
