//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerithium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes_Specialisations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classes_Specialisations()
        {
            this.Characters_Specialisations = new HashSet<Characters_Specialisations>();
        }
    
        public int id { get; set; }
        public int class_id { get; set; }
        public int spec_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Characters_Specialisations> Characters_Specialisations { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Specialisations Specialisations { get; set; }
    }
}
