//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerithium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Signups
    {
        public int id { get; set; }
        public int event_id { get; set; }
        public int character_id { get; set; }
        public int status_id { get; set; }
        public int person_id { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual Events Events { get; set; }
        public virtual People People { get; set; }
        public virtual Signup_Status Signup_Status { get; set; }
    }
}
